# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("check_plus_in_primary_fur_color works", {
  expect_true(inherits(check_plus_in_primary_fur_color, "function"))
  
  expect_false(check_plus_in_primary_fur_color("coucou+coucou"))
  expect_true(check_plus_in_primary_fur_color("coucou"))

  
  expect_error(object = check_plus_in_primary_fur_color(c(12, 22)),
               regexp = "primary_fur_color should be a character")
})
