# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_df_nrows works", {

  expect_message(
    object = get_df_nrows(df = mtcars),
    regexp = "The dataset is composed of 32 observations"
    
  )
  
})
