# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("check_coordinates works", {
  expect_true(inherits(check_coordinates, "function"))
  
    expect_error(object = check_coordinates("J'aime les écureuils", "roux"),
               regexp = "latitude and longitude should be numeric")
  
  
})
