# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("check_presence_of_required_columns works", {
  
  nyc_squirrels_sample <- readr::read_csv(system.file("nyc_squirrels_sample.csv", package = "squirrels"))
  expect_true(object = check_presence_of_required_columns(df = nyc_squirrels_sample)) 
})
