# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand # nolint: line_length_linter.

#' get_df_nrows
#' 
#' Compute number of rows
#' 
#' @param df data.frame
#'
#' @return nrow Number of rows
#' @importFrom glue glue
#' @export
#' @examples
#' get_df_nrows(df = mtcars)

get_df_nrows <- function(df){
  nrow <- nrow(df)
  message(glue::glue("The dataset is composed of {nrow} observations"))
  return(nrow) 
}
